import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ThemeProvider, createTheme } from '@mui/material/styles';
import CssBaseline from '@mui/material/CssBaseline';
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
const darkTheme = createTheme({
  palette: {
    mode: 'dark',
  },
  spacing: 8
});

export const metadata: Metadata = {
  title: "NextFintracker",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ThemeProvider theme={darkTheme}>
      <html lang="en">
        <CssBaseline enableColorScheme />
        <body className={inter.className}>{children}</body>
      </html>
    </ThemeProvider>
  );
}
